// Code generated by hertz generator.

package idlManager

import (
	"context"

	idlManager "github.com/SchrodingerwithCat/CloudWeGoFinalProj/gateway/biz/model/hertzSvr/idlManager"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UpdateIDL .
// @router /idl/update [POST]
func UpdateIDL(ctx context.Context, c *app.RequestContext) {
	var err error
	var req idlManager.IDLMessage
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(idlManager.IDLResponse)

	c.JSON(consts.StatusOK, resp)
}
